global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'website'
    static_configs:
      - targets: ['website:80']
    metrics_path: /api/metrics

  - job_name: 'game-backend'
    static_configs:
      - targets: ['game-backend:3001']
    metrics_path: /metrics

  - job_name: 'game-client'
    static_configs:
      - targets: ['game-client:80']
    metrics_path: /metrics

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
